type Optional<T> = T | null;

export interface Format {
    fps?:                Optional<number>,
    asr?:                Optional<number>,
    height?:             Optional<number>,
    width?:              Optional<number>,
    abr?:                Optional<number>,
    protocol?:           Optional<string>,
    filesize?:           Optional<number>,
    downloader_options?: Optional<Object>,
    format?:             Optional<string>,
    format_note?:        Optional<string>,
    vcodec?:             Optional<string>,
    format_id?:          Optional<string>,
    acodec?:             Optional<string>,
    ext?:                Optional<string>,
    player_url?:         Optional<string>,
    url?:                Optional<string>,
    tbr?:                Optional<number>,
    http_headers?:       Optional<Object>
}

export interface Thumbnail {
    id:                 number,
    width:              number,
    url:                string,
    height:             number,
    resolution:         string
}

export interface Metadata { 
    categories?:            Optional<string>[],
    like_count?:            Optional<number>,
    end_time?:              Optional<number>,
    annotations?:           any,
    acodec?:                Optional<string>,
    fps?:                   Optional<number>,
    episode_number?:        Optional<number>,
    vcodec?:                Optional<string>,
    extractor?:             Optional<string>,
    formats?:               Format[],
    channel_id?:            Optional<string>,
    release_year?:          any,
    creator?:               any,
    license?:               any,
    duration?:              Optional<number>,
    start_time?:            any,
    thumbnails?:            Thumbnail[],
    id?:                    Optional<string>,
    requested_formats?:     Format[],
    requested_subtitles?:   any,
    display_id?:            Optional<string>,
    playlist_index?:        any,
    resolution?:            any,
    stretched_ratio?:       any,
    format_id?:             Optional<string>,
    playlist?:              any,
    height?:                Optional<number>,
    release_date?:          any,
    thumbnail?:             Optional<string>,
    artist?:                any,
    track?:                 any,
    is_live?:               any,
    width?:                 Optional<number>,
    tags?:                  Optional<string>[],
    uploader_url?:          Optional<string>,
    channel_url?:           Optional<string>,
    abr?:                   Optional<number>,
    upload_date?:           Optional<string>,
    average_rating?:        Optional<number>,
    uploader?:              Optional<string>,
    description?:           Optional<string>,
    vbr:                    null,
    subtitles:              Optional<Object>,
    extractor_key:          Optional<string>,
    title:                  Optional<string>,
    automatic_captions:     Optional<Object>,
    series:                 any,
    season_number:          any,
    dislike_count:          any,
    alt_title:              any,
    chapters:               any,
    view_count:             Optional<number>,
    format:                 Optional<string>,
    ext:                    Optional<string>,
    webpage_url:            Optional<string>,
    album:                  any,
    webpage_url_basename:   Optional<string>,
    uploader_id:            Optional<string>,
    age_limit:              Optional<number>
  }